import type { Handler } from "@netlify/functions";
import { Redis } from "@upstash/redis";
import { randomUUID, createHash } from "node:crypto";
import { createVeoVideo } from "./providers/veo";
import { createPixVerseVideo } from "./providers/pixverse";
const redis=Redis.fromEnv();const QUEUE_KEY="video-generation-queue";const JOB_TTL=86400;const MAX_DURATION_SECONDS=300;const MAX_CLIPS=120;
type Provider="veo"|"pixverse";
const json=(statusCode:number,body:unknown)=>({statusCode,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type, Authorization, X-API-Key","Access-Control-Allow-Methods":"GET, POST, OPTIONS"},body:JSON.stringify(body)});
function apiKeys():string[]{return[process.env.FRUITYSTORY_API_KEY,process.env.FRUITYSTORY_API_KEYS].filter(Boolean).flatMap(v=>String(v).split(",")).map(v=>v.trim()).filter(Boolean)}
function getApiKey(event:Parameters<Handler>[0]){const auth=event.headers.authorization||event.headers.Authorization||"";return(event.headers["x-api-key"]||event.headers["X-API-Key"]||auth.replace(/^Bearer\s+/i,"")).trim()}
function authorized(event:Parameters<Handler>[0]){const key=getApiKey(event);return Boolean(key&&apiKeys().includes(key))}function ownerId(key:string){return`api:${createHash("sha256").update(key).digest("hex").slice(0,32)}`}
function provider(value:unknown):Provider{const normalized=String(value||"veo").toLowerCase();if(normalized!=="veo"&&normalized!=="pixverse")throw new Error("provider doit être 'veo' ou 'pixverse'.");return normalized}
function makePrompts(body:any,providerName:Provider){if(Array.isArray(body.clips)&&body.clips.length){const prompts=body.clips.map((c:any)=>typeof c==="string"?c.trim():String(c?.prompt||"").trim()).filter(Boolean);if(!prompts.length)throw new Error("clips ne contient aucun prompt valide.");return prompts.slice(0,MAX_CLIPS)}const duration=Math.max(1,Math.min(MAX_DURATION_SECONDS,Math.ceil(Number(body.durationSeconds??body.duration??8))));const sceneSeconds=providerName==="pixverse"?15:8;const count=Math.min(MAX_CLIPS,Math.ceil(duration/sceneSeconds));return Array.from({length:count},(_,i)=>`${String(body.prompt).trim()}\nScène ${i+1}/${count}. Continuité visuelle avec les scènes précédentes.`)}
async function startClip(providerName:Provider,prompt:string,body:any){if(providerName==="veo")return createVeoVideo({prompt,aspectRatio:body.aspectRatio==="9:16"?"9:16":"16:9",resolution:["720p","1080p","4k"].includes(body.resolution)?body.resolution:"720p"});return createPixVerseVideo({prompt,model:body.model==="c1"?"c1":"v6",duration:Math.max(1,Math.min(15,Math.floor(Number(body.sceneDurationSeconds??15)))),quality:["360p","540p","720p","1080p"].includes(body.quality)?body.quality:"720p",aspectRatio:body.aspectRatio||"9:16",generateAudio:typeof body.generateAudio==="boolean"?body.generateAudio:undefined,generateMultiClip:typeof body.generateMultiClip==="boolean"?body.generateMultiClip:undefined})}
export const handler:Handler=async event=>{if(event.httpMethod==="OPTIONS")return json(204,null);if(!authorized(event))return json(401,{success:false,error:"API key FruityStory invalide ou non configurée."});const path=(event.path||"").replace(/^.*\/provider-api\/?/,"").replace(/^\/api\/v1\/?/,"").split("/").filter(Boolean);const key=getApiKey(event);const userId=ownerId(key);try{if(event.httpMethod==="GET"&&path[0]==="providers")return json(200,{success:true,provider:"fruitystory",providers:[{id:"veo",name:"Google Veo",capabilities:["text-to-video","multi-clip","assembly","retrieval"]},{id:"pixverse",name:"PixVerse",capabilities:["text-to-video","multi-clip","assembly","retrieval"]}],limits:{maxDurationSeconds:MAX_DURATION_SECONDS,maxClips:MAX_CLIPS}});
 if(event.httpMethod==="POST"&&path[0]==="videos"&&(path[1]==="generations"||!path[1])){const body=event.body?JSON.parse(event.body):{};const prompt=typeof body.prompt==="string"?body.prompt.trim():"";if(!prompt&&!Array.isArray(body.clips))return json(400,{success:false,error:"prompt ou clips est obligatoire."});const selected=provider(body.provider);if(selected==="veo"&&!process.env.GEMINI_API_KEY)return json(500,{success:false,error:"GEMINI_API_KEY manquante côté serveur."});if(selected==="pixverse"&&!process.env.PIXVERSE_API_KEY)return json(500,{success:false,error:"PIXVERSE_API_KEY manquante côté serveur."});const prompts=makePrompts(body,selected);const requestedDuration=Number(body.durationSeconds??body.duration??prompts.length*(selected==="pixverse"?15:8));if(!Number.isFinite(requestedDuration)||requestedDuration<=0||requestedDuration>MAX_DURATION_SECONDS)return json(400,{success:false,error:`durationSeconds doit être compris entre 1 et ${MAX_DURATION_SECONDS}.`});const clips:any[]=[];for(let index=0;index<prompts.length;index++){const job:any=await startClip(selected,prompts[index],body);const operationId=selected==="veo"?job.operationName:job.videoId;if(!operationId)throw new Error(`${selected} n'a pas retourné d'identifiant de génération.`);clips.push({index,prompt:prompts[index],operationId,status:"queued"})}const jobId=randomUUID();await redis.set(`video-job:${jobId}`,{jobId,userId,tier:"api",provider:selected,model:selected==="veo"?(process.env.GEMINI_VIDEO_MODEL||"veo-3.1-generate-preview"):(body.model==="c1"?"c1":"v6"),status:"queued",prompt:prompt||"multi-clip",clips,requestedDurationSeconds:requestedDuration,completedClipUrls:[],createdAt:new Date().toISOString()},{ex:JOB_TTL});await redis.rpush(QUEUE_KEY,jobId);return json(202,{success:true,jobId,provider:selected,status:"queued",clipCount:clips.length,requestedDurationSeconds:requestedDuration,statusEndpoint:`/api/v1/videos/generations/${encodeURIComponent(jobId)}`,retrievalEndpoint:`/api/v1/videos/generations/${encodeURIComponent(jobId)}/download`})}
 if(event.httpMethod==="GET"&&path[0]==="videos"&&path[1]==="generations"&&path[2]&&path[3]==="download"){const job=await redis.get<any>(`video-job:${path[2]}`);if(!job||job.userId!==userId)return json(404,{success:false,error:"Job introuvable."});if(job.status!=="completed"||!job.finalVideoUrl)return json(409,{success:false,error:"La vidéo finale n'est pas encore disponible.",status:job.status});return{statusCode:302,headers:{Location:job.finalVideoUrl,"Cache-Control":"no-store"},body:""}}
 if(event.httpMethod==="GET"&&path[0]==="videos"&&path[1]==="generations"&&path[2]){const job=await redis.get<any>(`video-job:${path[2]}`);if(!job||job.userId!==userId)return json(404,{success:false,error:"Job introuvable."});return json(200,{success:true,jobId:job.jobId,status:job.status,provider:job.provider,clipCount:job.clips?.length||0,completedClips:job.clips?.filter((c:any)=>c.status==="completed").length||0,finalVideoUrl:job.finalVideoUrl||null,outputUrl:job.finalVideoUrl||null,downloadEndpoint:job.status==="completed"?`/api/v1/videos/generations/${encodeURIComponent(job.jobId)}/download`:null,error:job.error||null})}
 return json(404,{success:false,error:"Endpoint API introuvable."})}catch(error){console.error("FruityStory Provider API error",error);return json(502,{success:false,error:error instanceof Error?error.message:"Provider error"})}};
export const config={path:"/api/v1/*"};
