import type { Handler } from "@netlify/functions";
import { Redis } from "@upstash/redis";
import { getStore } from "@netlify/blobs";
import { getVeoVideoStatus } from "./providers/veo";
import { getPixVerseVideoStatus } from "./providers/pixverse";
import { assembleVideoClips } from "./lib/assemble-video";
const redis=Redis.fromEnv();const videos=getStore({name:"fruitystory-videos",consistency:"strong"});const QUEUE_KEY="video-generation-queue";const JOB_TTL=86400;
type ClipJob={index:number;prompt:string;operationId:string;status:"queued"|"processing"|"completed"|"failed";url?:string;error?:string};
function json(statusCode:number,body:unknown){return{statusCode,headers:{"Content-Type":"application/json","Cache-Control":"no-store","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, authorization","Access-Control-Allow-Methods":"POST, OPTIONS"},body:JSON.stringify(body)}}
function extractVeoUrl(result:any):string|null{return result?.response?.generateVideoResponse?.generatedSamples?.[0]?.video?.uri||result?.response?.generatedVideos?.[0]?.video?.uri||result?.operation?.response?.generateVideoResponse?.generatedSamples?.[0]?.video?.uri||result?.operation?.response?.generatedVideos?.[0]?.video?.uri||result?.generatedVideos?.[0]?.video?.uri||null}
async function releaseReservationIfNeeded(job:any){if(job.quotaReleased||!job.quotaKey)return;const current=Number((await redis.get<number>(job.quotaKey))??0);if(current>0)await redis.decr(job.quotaKey);await redis.set(`video-job:${job.jobId}`,{...job,quotaReleased:true},{ex:JOB_TTL})}
async function processJob(jobId:string){const key=`video-job:${jobId}`;const job:any=await redis.get(key);if(!job)return{jobId,status:"missing"};if(job.status==="completed")return{jobId,status:"completed",finalVideoUrl:job.finalVideoUrl};if(job.status==="failed")return{jobId,status:"failed",error:job.error};const clips:ClipJob[]=Array.isArray(job.clips)?job.clips:[];if(!clips.length)throw new Error("Job sans clips.");let changed=false;for(let i=0;i<clips.length;i++){const clip=clips[i];if(clip.status==="completed")continue;const result:any=job.provider==="pixverse"?await getPixVerseVideoStatus(clip.operationId):await getVeoVideoStatus(clip.operationId);const status=String(result?.status||"").toLowerCase();const failed=status==="failed"||status==="error"||Boolean(result?.error);if(failed){const errorMessage=String(result?.error||`Clip ${i+1} échoué.`);const failedClips=clips.map((c,index)=>index===i?{...c,status:"failed" as const,error:errorMessage}:c);const failedJob={...job,clips:failedClips,status:"failed",error:errorMessage};await redis.set(key,failedJob,{ex:JOB_TTL});await releaseReservationIfNeeded(failedJob);await redis.lrem(QUEUE_KEY,0,jobId);return{jobId,status:"failed",error:errorMessage}}const completed=job.provider==="pixverse"?status==="completed"&&Boolean(result?.url):Boolean(result?.done)&&Boolean(extractVeoUrl(result));if(!completed){if(clip.status!=="processing"){clips[i]={...clip,status:"processing"};changed=true}continue}const url=job.provider==="pixverse"?String(result.url):extractVeoUrl(result);if(!url)continue;clips[i]={...clip,status:"completed",url};changed=true}
 if(changed)await redis.set(key,{...job,clips,status:"processing"},{ex:JOB_TTL});if(clips.some(c=>c.status!=="completed"))return{jobId,status:"processing",completedClips:clips.filter(c=>c.status==="completed").length,totalClips:clips.length};const clipUrls=clips.sort((a,b)=>a.index-b.index).map(c=>c.url).filter((url):url is string=>Boolean(url));try{const finalBuffer=await assembleVideoClips(clipUrls);const blobKey=`videos/${job.userId}/${jobId}.mp4`;await videos.set(blobKey,new Blob([new Uint8Array(finalBuffer)]),{metadata:{contentType:"video/mp4",jobId,userId:String(job.userId),provider:String(job.provider),createdAt:new Date().toISOString()}});const siteUrl=process.env.URL||process.env.DEPLOY_PRIME_URL;if(!siteUrl)throw new Error("URL Netlify manquante.");const finalVideoUrl=`${siteUrl.replace(/\/$/,"")}/.netlify/functions/video-file?key=${encodeURIComponent(blobKey)}`;await redis.set(key,{...job,clips,status:"completed",finalVideoUrl,blobKey,completedAt:new Date().toISOString()},{ex:JOB_TTL});await redis.lrem(QUEUE_KEY,0,jobId);return{jobId,status:"completed",finalVideoUrl}}catch(error){const message=error instanceof Error?error.message:"Assemblage vidéo échoué.";const failedJob={...job,clips,status:"failed",error:message};await redis.set(key,failedJob,{ex:JOB_TTL});await releaseReservationIfNeeded(failedJob);await redis.lrem(QUEUE_KEY,0,jobId);return{jobId,status:"failed",error:message}}
}
export const handler:Handler=async event=>{if(event.httpMethod==="OPTIONS")return json(204,null);if(event.httpMethod!=="POST")return json(405,{success:false,error:"Utilisez POST."});let body:any={};try{body=event.body?JSON.parse(event.body):{}}catch{return json(400,{success:false,error:"JSON invalide."})}const requested=typeof body.jobId==="string"?[body.jobId]:[];const ids=requested.length?requested:((await redis.lrange<string>(QUEUE_KEY,0,9))||[]);const processed=[];for(const id of ids){try{processed.push(await processJob(id))}catch(error){processed.push({jobId:id,status:"error",error:error instanceof Error?error.message:"Worker error"})}}return json(200,{success:true,processed})};
