import type { PoolClient } from 'pg';
import { db } from './db';

export async function getUser(id: string) { const r=await db().query('SELECT id,username,email,display_name AS "displayName",bio,avatar_url AS "avatarUrl",verified,followers_count AS followers,following_count AS following,likes_count AS likes FROM users WHERE id=$1',[id]); return r.rows[0]??null; }
export async function getUserByLogin(login: string) { const r=await db().query('SELECT * FROM users WHERE email=$1 OR username=$1 LIMIT 1',[login]); return r.rows[0]??null; }
export async function createUser(username:string,email:string,passwordHash:string) { const r=await db().query('INSERT INTO users(username,email,password_hash,display_name) VALUES($1,$2,$3,$1) RETURNING id,username,email,display_name AS "displayName",bio,avatar_url AS "avatarUrl",verified,followers_count AS followers,following_count AS following,likes_count AS likes',[username,email,passwordHash]); return r.rows[0]; }
export async function feed(limit=20, cursor?:string) { const args:any[]=[limit]; let where="v.visibility='public'"; if(cursor){args.push(cursor);where+=' AND v.created_at < $2';} const r=await db().query(`SELECT v.id,v.author_id AS "authorId",v.video_url AS "videoUrl",v.thumbnail_url AS "thumbnailUrl",v.caption,v.visibility,v.allow_comments AS "allowComments",v.allow_duet AS "allowDuet",v.allow_stitch AS "allowStitch",v.allow_download AS "allowDownload",v.views_count AS views,v.likes_count AS likes,v.comments_count AS comments,v.shares_count AS shares,v.created_at AS "createdAt" FROM videos v WHERE ${where} ORDER BY v.created_at DESC LIMIT $1`,args); return r.rows; }
export async function createVideo(client:PoolClient|typeof db, userId:string, input:any){ const q=client as any; const r=await q.query('INSERT INTO videos(author_id,video_url,thumbnail_url,caption,visibility,allow_comments,allow_duet,allow_stitch,allow_download) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[userId,input.videoUrl,input.thumbnailUrl??null,input.caption??'',input.visibility??'public',input.allowComments!==false,input.allowDuet!==false,input.allowStitch!==false,input.allowDownload===true]); return r.rows[0]; }
export async function likeVideo(userId:string,videoId:string){ const c=await db().connect(); try{await c.query('BEGIN');const ins=await c.query('INSERT INTO video_likes(video_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[videoId,userId]);if(ins.rowCount){await c.query('UPDATE videos SET likes_count=likes_count+1 WHERE id=$1',[videoId]);}await c.query('COMMIT');return !!ins.rowCount;}catch(e){await c.query('ROLLBACK');throw e}finally{c.release();} }
export async function unlikeVideo(userId:string,videoId:string){const c=await db().connect();try{await c.query('BEGIN');const d=await c.query('DELETE FROM video_likes WHERE video_id=$1 AND user_id=$2',[videoId,userId]);if(d.rowCount)await c.query('UPDATE videos SET likes_count=GREATEST(0,likes_count-1) WHERE id=$1',[videoId]);await c.query('COMMIT');return !!d.rowCount;}catch(e){await c.query('ROLLBACK');throw e}finally{c.release();}}
export async function addComment(userId:string,videoId:string,body:string,parentId?:string){const r=await db().query('INSERT INTO comments(video_id,author_id,body,parent_id) VALUES($1,$2,$3,$4) RETURNING id,video_id AS "videoId",author_id AS "authorId",body,parent_id AS "parentId",likes_count AS likes,created_at AS "createdAt"',[videoId,userId,body,parentId??null]);await db().query('UPDATE videos SET comments_count=comments_count+1 WHERE id=$1',[videoId]);return r.rows[0];}
export async function comments(videoId:string){const r=await db().query('SELECT id,video_id AS "videoId",author_id AS "authorId",body,parent_id AS "parentId",likes_count AS likes,created_at AS "createdAt" FROM comments WHERE video_id=$1 ORDER BY created_at DESC',[videoId]);return r.rows;}
export async function follow(userId:string,targetId:string){const c=await db().connect();try{await c.query('BEGIN');const r=await c.query('INSERT INTO follows(follower_id,following_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[userId,targetId]);if(r.rowCount){await c.query('UPDATE users SET following_count=following_count+1 WHERE id=$1',[userId]);await c.query('UPDATE users SET followers_count=followers_count+1 WHERE id=$1',[targetId]);}await c.query('COMMIT');return !!r.rowCount;}catch(e){await c.query('ROLLBACK');throw e}finally{c.release();}}
export async function unfollow(userId:string,targetId:string){const c=await db().connect();try{await c.query('BEGIN');const r=await c.query('DELETE FROM follows WHERE follower_id=$1 AND following_id=$2',[userId,targetId]);if(r.rowCount){await c.query('UPDATE users SET following_count=GREATEST(0,following_count-1) WHERE id=$1',[userId]);await c.query('UPDATE users SET followers_count=GREATEST(0,followers_count-1) WHERE id=$1',[targetId]);}await c.query('COMMIT');return !!r.rowCount;}catch(e){await c.query('ROLLBACK');throw e}finally{c.release();}}
